In [3]:
import numpy as np

In [4]:
#Creating Numpy Array
mylist = [1,2,3]
myarr = np.array(mylist)

In [5]:
type(myarr)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
type(my_matrix)


list

In [7]:
my_matrix = np.array(my_matrix)
type(my_matrix)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8]]
#type(my_matrix)


In [10]:
my_matrix = np.array(my_matrix)   #Array of Lists i.e. 1D array
#type(my_matrix)
print(my_matrix)     
#my_matrix.shape


[list([1, 2, 3]) list([4, 5, 6]) list([7, 8])]


In [12]:
np.arange(0,10,2)
# np.arange(0,10,2).shape  out = (5,) for 1 d array



(5,)

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
ar = np.random.rand(5,3)
ar

array([[0.0884925 , 0.19598286, 0.04522729],
       [0.32533033, 0.38867729, 0.27134903],
       [0.82873751, 0.35675333, 0.28093451],
       [0.54269608, 0.14092422, 0.80219698],
       [0.07455064, 0.98688694, 0.77224477]])

In [53]:
ar.dtype

dtype('float64')

In [25]:
np.random.randn(2,3)

array([[-0.12260773,  0.17468532,  1.95746809],
       [ 1.28633464,  1.95241537,  0.78794016]])

In [31]:
np.random.randint(2,101,10)

array([81, 60, 68, 13, 34, 63, 80, 42, 57, 16])

In [33]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [38]:
arr = np.arange(0,25)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr.dtype

dtype('int32')

In [14]:
ranarr = np.random.randint(0,101)

In [15]:
ranarr

59

In [42]:
ranarr.max()

99

In [43]:
ranarr.min()

2

In [44]:
ranarr.argmax()  # to find the indiex of max value in ranarr

5

In [46]:
ranarr.argmin() # to find the index of min value in ranarr

7

In [47]:
ranarr.dtype   # to fetch the data type of the array

dtype('int32')

In [54]:
ranarr.shape

(10,)

In [57]:
ranarr = ranarr.reshape(2,5)

In [58]:
ranarr.shape

(2, 5)