In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
#Broadcasting
arr[0:5] =100   # Not possible in list 

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr = np.arange(0,11)

In [12]:
arr_slice =arr[:5]   #In numpy thr sliced array points to the original location 
                        #changes to this arr_slice will affect the arr(original) aray

In [18]:
arr_slice

array([99, 99, 99, 99, 99])

In [14]:
arr_slice[:] = 99

In [15]:
arr    #elements refered by arr_slice are affected

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [19]:
# to not affect the original array Create the copy
arr_copy = arr.copy()


In [20]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [21]:
arr_copy =100


In [22]:
arr_copy

100

In [23]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [26]:
#Indexing on 2D array


In [31]:
arr = np.arange(9)

In [34]:
arr_2d = arr.reshape(3,3)

In [37]:
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [36]:
arr_2d[2][1]

7

In [38]:
arr_2d[2,1]

7

In [40]:
arr_2d[:2,1:]

array([[1, 2],
       [4, 5]])

In [41]:
arr =np.arange(1,11)

In [47]:
arr[7:] = 68

In [48]:
arr > 4 

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [49]:
bool_arr = arr >4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [50]:
arr[bool_arr]   # gives out the values where bool_arr is true  -- its like filtering

array([ 5,  6,  7, 68, 68, 68])