In [1]:
import numpy as np


In [3]:
arr =np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr + 5  # add 5 to each element of arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
arr + arr  # to add arrays they should be of same shape

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr / arr

C:\Users\shiva\AppData\Local\Temp\ipykernel_21428\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [8]:
arr // arr

C:\Users\shiva\AppData\Local\Temp\ipykernel_21428\376544773.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  arr // arr


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [9]:
1 / 0 

ZeroDivisionError: division by zero

In [11]:
arr_res = 1 / arr 

C:\Users\shiva\AppData\Local\Temp\ipykernel_21428\1706491487.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr_res = 1 / arr


In [17]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr.sum()

45

In [20]:
arr.mean()

4.5

In [21]:
arr.max()


9

In [22]:
arr.var(0)

8.25

In [23]:
arr.std()

2.8722813232690143

In [24]:
# In  2D array

In [25]:
arr2d = np.arange(0,25).reshape(5,5)

In [26]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr2d.sum()   # sum of all numbers


300

In [29]:
arr2d.sum(axis = 0)    # gives out the sum of the columns i.e across rows

array([50, 55, 60, 65, 70])

In [30]:
arr2d.sum(axis = 1)  # sum of rows i.e. sum across columns

array([ 10,  35,  60,  85, 110])